# NewsomeP2
# Programmer: Corrigan Newsome
# Email: cnewsome2@cnm.edu
# Purpose: To use lists and indexing to select states, capitals, districts, and order of entry into union.


# 1. Your program will initialize lists to store information about the states.
# You should have one list for the names of the states,
# one list for the names of the capitals,
# one list for the number of districts per state and one list
# for the order number the state joined the union.
# Alternatively you can use a db list of lists as demonstrated in the
# exercises in the book to store the information in one structure.

states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

captials = (
    "Montgomery",
    "Juneau",
    "Phoenix",
    "Little Rock",
    "Sacramento",
    "Denver",
    "Hartford",
    "Dover",
    "Tallahassee",
    "Atlanta",
    "Honolulu",
    "Boise",
    "Springfield",
    "Indianapolis",
    "Des Moines",
    "Topeka",
    "Frankfort",
    "Baton Rouge",
    "Augusta",
    "Annapolis",
    "Boston",
    "Lansing",
    "Saint Paul",
    "Jackson",
    "Jefferson City",
    "Helena",
    "Lincoln",
    "Carson City",
    "Concord ",
    "Trenton",
    "Santa Fe",
    "Albany",
    "Raleigh",
    "Bismarck",
    "Columbus",
    "Oklahoma City",
    "Salem",
    "Harrisburg",
    "Providence",
    "Columbia",
    "Pierre",
    "Nashville",
    "Austin",
    "Salt Lake City",
    "Montpelier",
    "Richmond",
    "Olympia",
    "Charleston",
    "Madison",
    "Cheyenne",
)

districs = (
    7,
    1,
    9,
    4,
    52,
    8,
    5,
    1,
    28,
    14,
    2,
    2,
    17,
    9,
    4,
    4,
    6,
    6,
    2,
    8,
    9,
    13,
    8,
    4,
    8,
    2,
    3,
    4,
    2,
    12,
    3,
    26,
    14,
    1,
    15,
    5,
    6,
    17,
    2,
    7,
    1,
    9,
    38,
    4,
    1,
    11,
    10,
    2,
    8,
    1,
)

order = (
    22,
    49,
    48,
    25,
    31,
    38,
    5,
    1,
    27,
    4,
    50,
    43,
    21,
    19,
    29,
    34,
    15,
    18,
    23,
    7,
    6,
    26,
    32,
    20,
    24,
    41,
    37,
    36,
    9,
    3,
    47,
    11,
    39,
    12,
    17,
    46,
    33,
    2,
    13,
    40,
    8,
    16,
    28,
    45,
    14,
    10,
    42,
    35,
    30,
    44,
)
# 2.	Next ask the user to enter a name of a state.

userInputState = input("Enter State name: (1-50)")

# 3.	Find the index of that name.
stateNumber = int(userInputState)
stateName = states[stateNumber - 1]


# 4.	Use that index to report back to the user the name of the capital,
# the number of congressional districts and the order the state joined the
# union.
capitalName = captials[stateNumber - 1]
districtName = districs[stateNumber - 1]
orderName = order[stateNumber - 1]
print(
    "The Capital of",
    stateName,
    "is",
    capitalName,
    "it has",
    districtName,
    "Congressional Districts and it is state number",
    orderName,
    "in the Union",
)
